### ISSUE TITLE
嘿~ 有兴趣合作吗？

### ISSUE THREAD

**Issue by eyenobig** [KazeMai/fgo-vz#1]
我是大陸這邊的攻略組
也製作了一個 手冊向的攻略書
fgo.eyenobig.com
如果可以我能讓你學習一下嗎？

**Comment by KazeMai** [comment]
之前就知道這程式
裡頭的內容已經挺完整的
我這邊應該沒什麼能再提供?

**Comment by eyenobig** [comment]
整理方面吧~因為我們不會破解這個遊戲
爬蟲也是藉用的或者手录 所以想了解一下您是用的什麼程式
如果可以能留下一個即時通訊的軟體嗎？

**Comment by KazeMai** [comment]
我是撈封包再自己解碼得來的資料
有QQ但很少開

**Comment by eyenobig** [comment]
我們這邊的解碼 只獲得了 圖片 和部分數據 
但是對於音頻和您那個 二維圖一直在找方法 
大陸這邊因為很多問題有梯子 line 是無法連接的 
qq：1120436134
